//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace PhaseFraction.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MWS_S1Soap", Namespace="http://tempuri.org/MWS_Services/MWS_S1")]
    public partial class MWS_S1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MWS_IO_POOL_INSERTOperationCompleted;
        
        private System.Threading.SendOrPostCallback mws_io_timingcheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Zvr_Up_file_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Zvr_New_VrOperationCompleted;
        
        private System.Threading.SendOrPostCallback UP_Zvr_up_sys_logOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MWS_S1() {
            this.Url = global::PhaseFraction.Properties.Settings.Default.YS_VSFC_WebReference_MWS_S1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MWS_IO_POOL_INSERTCompletedEventHandler MWS_IO_POOL_INSERTCompleted;
        
        /// <remarks/>
        public event mws_io_timingcheckCompletedEventHandler mws_io_timingcheckCompleted;
        
        /// <remarks/>
        public event Get_Zvr_Up_file_listCompletedEventHandler Get_Zvr_Up_file_listCompleted;
        
        /// <remarks/>
        public event Get_Zvr_New_VrCompletedEventHandler Get_Zvr_New_VrCompleted;
        
        /// <remarks/>
        public event UP_Zvr_up_sys_logCompletedEventHandler UP_Zvr_up_sys_logCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MWS_Services/MWS_S1/MWS_IO_POOL_INSERT", RequestNamespace="http://tempuri.org/MWS_Services/MWS_S1", ResponseNamespace="http://tempuri.org/MWS_Services/MWS_S1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MWS_IO_POOL_INSERT(string mac, string barcode, string uptime) {
            object[] results = this.Invoke("MWS_IO_POOL_INSERT", new object[] {
                        mac,
                        barcode,
                        uptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MWS_IO_POOL_INSERTAsync(string mac, string barcode, string uptime) {
            this.MWS_IO_POOL_INSERTAsync(mac, barcode, uptime, null);
        }
        
        /// <remarks/>
        public void MWS_IO_POOL_INSERTAsync(string mac, string barcode, string uptime, object userState) {
            if ((this.MWS_IO_POOL_INSERTOperationCompleted == null)) {
                this.MWS_IO_POOL_INSERTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMWS_IO_POOL_INSERTOperationCompleted);
            }
            this.InvokeAsync("MWS_IO_POOL_INSERT", new object[] {
                        mac,
                        barcode,
                        uptime}, this.MWS_IO_POOL_INSERTOperationCompleted, userState);
        }
        
        private void OnMWS_IO_POOL_INSERTOperationCompleted(object arg) {
            if ((this.MWS_IO_POOL_INSERTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MWS_IO_POOL_INSERTCompleted(this, new MWS_IO_POOL_INSERTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MWS_Services/MWS_S1/mws_io_timingcheck", RequestNamespace="http://tempuri.org/MWS_Services/MWS_S1", ResponseNamespace="http://tempuri.org/MWS_Services/MWS_S1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string mws_io_timingcheck(string mac, string barcode, string uptime) {
            object[] results = this.Invoke("mws_io_timingcheck", new object[] {
                        mac,
                        barcode,
                        uptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mws_io_timingcheckAsync(string mac, string barcode, string uptime) {
            this.mws_io_timingcheckAsync(mac, barcode, uptime, null);
        }
        
        /// <remarks/>
        public void mws_io_timingcheckAsync(string mac, string barcode, string uptime, object userState) {
            if ((this.mws_io_timingcheckOperationCompleted == null)) {
                this.mws_io_timingcheckOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmws_io_timingcheckOperationCompleted);
            }
            this.InvokeAsync("mws_io_timingcheck", new object[] {
                        mac,
                        barcode,
                        uptime}, this.mws_io_timingcheckOperationCompleted, userState);
        }
        
        private void Onmws_io_timingcheckOperationCompleted(object arg) {
            if ((this.mws_io_timingcheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mws_io_timingcheckCompleted(this, new mws_io_timingcheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MWS_Services/MWS_S1/Get_Zvr_Up_file_list", RequestNamespace="http://tempuri.org/MWS_Services/MWS_S1", ResponseNamespace="http://tempuri.org/MWS_Services/MWS_S1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_Zvr_Up_file_list(string Mac, string Sysname, string NowVr) {
            object[] results = this.Invoke("Get_Zvr_Up_file_list", new object[] {
                        Mac,
                        Sysname,
                        NowVr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Zvr_Up_file_listAsync(string Mac, string Sysname, string NowVr) {
            this.Get_Zvr_Up_file_listAsync(Mac, Sysname, NowVr, null);
        }
        
        /// <remarks/>
        public void Get_Zvr_Up_file_listAsync(string Mac, string Sysname, string NowVr, object userState) {
            if ((this.Get_Zvr_Up_file_listOperationCompleted == null)) {
                this.Get_Zvr_Up_file_listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Zvr_Up_file_listOperationCompleted);
            }
            this.InvokeAsync("Get_Zvr_Up_file_list", new object[] {
                        Mac,
                        Sysname,
                        NowVr}, this.Get_Zvr_Up_file_listOperationCompleted, userState);
        }
        
        private void OnGet_Zvr_Up_file_listOperationCompleted(object arg) {
            if ((this.Get_Zvr_Up_file_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Zvr_Up_file_listCompleted(this, new Get_Zvr_Up_file_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MWS_Services/MWS_S1/Get_Zvr_New_Vr", RequestNamespace="http://tempuri.org/MWS_Services/MWS_S1", ResponseNamespace="http://tempuri.org/MWS_Services/MWS_S1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Zvr_New_Vr(string mac, string Sysname, string OldVr) {
            object[] results = this.Invoke("Get_Zvr_New_Vr", new object[] {
                        mac,
                        Sysname,
                        OldVr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Zvr_New_VrAsync(string mac, string Sysname, string OldVr) {
            this.Get_Zvr_New_VrAsync(mac, Sysname, OldVr, null);
        }
        
        /// <remarks/>
        public void Get_Zvr_New_VrAsync(string mac, string Sysname, string OldVr, object userState) {
            if ((this.Get_Zvr_New_VrOperationCompleted == null)) {
                this.Get_Zvr_New_VrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Zvr_New_VrOperationCompleted);
            }
            this.InvokeAsync("Get_Zvr_New_Vr", new object[] {
                        mac,
                        Sysname,
                        OldVr}, this.Get_Zvr_New_VrOperationCompleted, userState);
        }
        
        private void OnGet_Zvr_New_VrOperationCompleted(object arg) {
            if ((this.Get_Zvr_New_VrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Zvr_New_VrCompleted(this, new Get_Zvr_New_VrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MWS_Services/MWS_S1/UP_Zvr_up_sys_log", RequestNamespace="http://tempuri.org/MWS_Services/MWS_S1", ResponseNamespace="http://tempuri.org/MWS_Services/MWS_S1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UP_Zvr_up_sys_log(string mac, string Sysname, string NewVr) {
            object[] results = this.Invoke("UP_Zvr_up_sys_log", new object[] {
                        mac,
                        Sysname,
                        NewVr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UP_Zvr_up_sys_logAsync(string mac, string Sysname, string NewVr) {
            this.UP_Zvr_up_sys_logAsync(mac, Sysname, NewVr, null);
        }
        
        /// <remarks/>
        public void UP_Zvr_up_sys_logAsync(string mac, string Sysname, string NewVr, object userState) {
            if ((this.UP_Zvr_up_sys_logOperationCompleted == null)) {
                this.UP_Zvr_up_sys_logOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUP_Zvr_up_sys_logOperationCompleted);
            }
            this.InvokeAsync("UP_Zvr_up_sys_log", new object[] {
                        mac,
                        Sysname,
                        NewVr}, this.UP_Zvr_up_sys_logOperationCompleted, userState);
        }
        
        private void OnUP_Zvr_up_sys_logOperationCompleted(object arg) {
            if ((this.UP_Zvr_up_sys_logCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UP_Zvr_up_sys_logCompleted(this, new UP_Zvr_up_sys_logCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MWS_IO_POOL_INSERTCompletedEventHandler(object sender, MWS_IO_POOL_INSERTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MWS_IO_POOL_INSERTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MWS_IO_POOL_INSERTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void mws_io_timingcheckCompletedEventHandler(object sender, mws_io_timingcheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mws_io_timingcheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mws_io_timingcheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Zvr_Up_file_listCompletedEventHandler(object sender, Get_Zvr_Up_file_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Zvr_Up_file_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Zvr_Up_file_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Zvr_New_VrCompletedEventHandler(object sender, Get_Zvr_New_VrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Zvr_New_VrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Zvr_New_VrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UP_Zvr_up_sys_logCompletedEventHandler(object sender, UP_Zvr_up_sys_logCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UP_Zvr_up_sys_logCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UP_Zvr_up_sys_logCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591